language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build()'
        - julia --project=docs/ docs/make.jl
      after_success:
        - julia --project=docs/ docs/deploy.jl

script:
    - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)'
after_success:
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
