language: julia
os:
    - linux
julia:
    - 1.0
    - 1.2
    - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
    - julia --project -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaFEM/Materials.jl"));
                          Pkg.build();
                          Pkg.test(; coverage=true)'
after_success:
    - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
